#ifndef GAMEPLAY_PLAYER_CHARS_CHARLIST
#define GAMEPLAY_PLAYER_CHARS_CHARLIST

enum CharID {
  DEFAULT,
  NEKO,
  // MYSTERY,
  // TIMELINE,
  AKSTAR,
  // CINNAMON,
  // META,
  // VAMPIRE,
  // AQUA,
  // GALAXY,
  // CUBE,
  // OUTLAW,
  // MEDIC,
  INFIN, // Aka. Infinity
  // ABSTRACT,
  XLAB, // Aka. [X]
  // HAVEN,
  // FLUTTER,
  // DEVOTION,
  // FANTASY,
  // RHYTICK

};

#endif /* GAMEPLAY_PLAYER_CHARS_CHARLIST */
