name: Meson Build And Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - name: Link Assets
        run: |
          mkdir build && cd build && ln -s ../assets ./assets && ln -s ../maps ./maps
      - name: Install Deps
        run: sudo apt install lua5.4 liblua5.4-dev libfreetype-dev libspdlog-dev
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          setup-options: -Dbacklib=headless
          meson-version: 0.63.2
          ninja-version: 1.11.1
